spring:

  application:
    name: demo


  oauth2:
    kakao:
      client-id: ${KAKAO_ID}
      client-secret: ${KAKAO_SECRET}
      redirect-uri: http://localhost:8080/api/auth/code/kakao
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me




  #redis 포트 번호 지정
  data:
    redis:
      host: localhost
      port: 6379

  # 구글 SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: skaudwns3@gmail.com
    password: ${MAIL_KEY}
    properties:
      mail:
        smtp:
          auth: true
          sgtarttls:
            enable: true


#swagger yaml 경로 설정
springdoc:
  swagger-ui:
    url: /restDocs/openapi3.yaml



jwt:
  secret: ${JWT_SECRET}


